### ISSUE TITLE
A good description of how to retain RSEs and the career path

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#104]
From the discussion two weeks ago, @tobyhodges had an idea on how to formulate sth. that sounds convincing of how to retain RSEs in academia and what would be good arguments to actually do this. I feel this should be part of the call for action paper and the organization paper.
related issues:
#78 #84 
pinging some contributors:
@mschwarzmeier @Bisaloo @jngrad @jlinx

**Comment by Bisaloo** [comment]
There are useful elements on this topic here: https://zenodo.org/record/8264153
