### ISSUE TITLE
conclusion for competencies

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#118]
We need to have a conclusion for the competencies paper.
Last week we decided to focus that our values and competencies should serve as traits that people can unify around and identify with. These are commonalities that are worth highlighting.

**Comment by jcohen02** [comment]
Notes from discussion:
 - Highlight that this is now an important part of the scientific process and vital for supporting the future of research. (@hvwaldow)
 - Knowledge of competencies and best practices amongst RSEs and other critical technical staff is also important for host institutions who need to ensure that their software and data outputs meet required approaches. (@jngrad)
