### ISSUE TITLE
synchronize ELIXIR framework with our competencies

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#126]
our appendix has the ELIXIR framework listed. It would be great to synchronize how their curriculum is a representation of our framework.

**Comment by CaptainSifff** [comment]
related: #15

**Comment by BeastyBlacksmith** [comment]
Just to get things clear. We are talking about https://elixir-europe.org, right?

**Comment by CaptainSifff** [comment]
Notifying @tobyhodges .

**Comment by ljgarcia** [comment]
It would be good to know what is the ELIXIR framework for RSEs. I am aware of (i) good practices and Software Management Plans for (mostly) researchers who develop code which could also include or be extended to RSEs. However, I do not think it has been proposed in the form of a framework. 

Another point to see wrt competencies, if not done yet, would be Skills4EOSC, not sure they have anything for RSEs

**Comment by CaptainSifff** [comment]
We are refering  to the bioexcel competencies over here: https://competency.ebi.ac.uk/framework/bioexcel/3.0/profiles/compare/10115/10117

**Comment by ljgarcia** [comment]
I was not aware of that framework, first time I see it. I can have a look to it  and to the curriculum proposed to see any mappings. I could start with it in about one week.

**Comment by CaptainSifff** [comment]
Thank You!
