### ISSUE TITLE
deRSE Unconference 2023 Breakout

### ISSUE THREAD

**Issue by tobyhodges** [CaptainSifff/paper_teaching-learning-RSE#130]
Here is the plan I have so far for the breakout next week:

- introductions: Toby, Florian, ask other authors to stand up/wave
- preparing a paper to describe a set of core compentencies needed for Research Software Engineering
- almost ready to upload to a Arxiv, share with wider (international) RSE community for feedback
- objectives for today:
  - gather feedback, perspectives on current content
  - fill in some of the gaps in the paper content
  - compare competencies listed in paper with those created elsewhere
- A bit more about the paper: a few slides from Florian
- break out into groups. reassure people that they can move groups whenever they like, but encourage it at the break. suggested topics:
  1. compare lists of competencies: this paper, UniverseHPC, RSE Toolkit project, ELIXIR framework, others?
  2. outline a curriculum that would teach these competencies to novices, e.g. an MSc curriculum (aim for half-page)
  3. describe an illustrative career path based on the competencies in the paper
  4. create some visual aids, e.g. 'skills wheels' for different specialisms within the core competencies, perhaps also extending beyond the core
  5. collect examples of existing qualifications, e.g. Masters programs
- at the end: give opportunities for people to present what they've done. ask them to tell us at least one hour before the end if they'll want to do this
- collect email addresses, GitHub usernames of any newcomers who wants to stay involved

**Comment by tobyhodges** [comment]
## Outline a curriculum

- Objective: briefly (~half a page) describe the outline of a curriculum that would prepare students to succeed in an RSEng career by teaching them the core competencies.

### what to read?

the whole paper is relevant but in particular https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/competencies.md#required-generic-rse-skills

you may also find https://carpentries.github.io/lesson-development-training/audience.html and https://carpentries.github.io/lesson-development-training/objectives.html useful

### other guidance

We recommend trying to follow this process:
  1. define target audience: what do they already know? what might they have studied before arriving (e.g. coming to a bachelor program from high school? coming from a domain-specific bachelors into a masters program?)
  2. define desired learning outcomes (high level): by the end of the course, what will students know how to do? Try to make these specific, measurable (use "action verbs" -  provides a pretty nice list), and attainable given expected prior knowledge of students and time available for your course.
  3. if you have time, try one or both of the following:
    1. match up your defined outcomes with the competencies listed in the paper
    2. "decompose" some of the high-level outcomes into more granular objectives: i.e. component knowledge/skills/abilities that students need to pick up on the way to attaining the high-level outcome

**Comment by tobyhodges** [comment]
## designing visual aids ("Artistry")

- Objective: design/create some visualisations to enhance the content of the paper.

### what to read?

the whole paper. when reading, try to identify concepts and passages that could be complemented by an accompanying visual.

### other guidance

Format: designs and outputs do not need to be finished product: even a photo of a sketch on paper/a whiteboard is great! If you do create something digital, please try to use open source tools (e.g. Inkscape, GIMP) and save & share the file as SVG to allow for further editing.

Some ideas for visualisations you could work on (though any other ideas are also welcome):

- example "skills wheels" for the RSE specialisations https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/competencies.md#rse-specializations
    - see https://rsetoolkit.github.io/rse-competencies-toolkit/profile.html for example, which is built from https://github.com/RSEToolkit/rse-competencies-toolkit using Chart.js 
    - another example of a skills wheel: https://zenodo.org/record/4437294#.ZFO3F-zMIc1
- Something to illustrate the "core" nature of these competencies e.g. among some specialisations/domains that expand beyond only the skills here

**Comment by tobyhodges** [comment]
## Comparing Competencies

- Objective: compare the competencies described in the paper with similar lists created by others elsewhere
    - to what extent are these different resources in agreement?
    - is anything unaccounted for in the paper?
    - how could the content in the paper be used to enhance other resources?

## what to read

the whole paper, with particular focus on the list of skill categories https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/competencies.md#required-generic-rse-skills and the description of skill development with experience/career progression https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/competencies.md#how-much-do-different-people-need-to-know

## other guidance

other resources to compare against:

- RSE Compentencies Toolkit:
  - https://docs.google.com/document/d/1syrY4gyaAcNuONK0ANUiHgHcbJ3P9RoqSjy57AjUsuM/edit#heading=h.nlkwx70wrmf
  - https://github.com/RSEToolkit/rse-competencies-toolkit/blob/main/_data/skills.json
- US-RSE Skills list:
  - https://us-rse.org/wg/education_training/skills/
- something from UniverseHPC?
- ELIXIR Competency Hub https://competency.ebi.ac.uk/framework/bioexcel/3.0
- Bioinformatics Mastery Rubric: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0225256#sec008
- Research Software (RS) Careers: Generic Learnings from King's Digital Lab: https://zenodo.org/record/2559235 (pages 14-18 in particular)
- Hiring, Managing, and Retaining Data Scientists and Research Software Engineers in Academia: https://zenodo.org/record/8264153 (pages 96-101 in particular)

**Comment by tobyhodges** [comment]
## Example career path

- Objective: tell the story of a archetypal career path through the "levels" described in the paper, and how the archetype's skills develop along the way.

### What to read

the whole paper is relevant but in particular https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/competencies.md#how-much-do-different-people-need-to-know 

also https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/competencies.md#rse-specializations so that you can choose a specialisation for your archetype to take.

### other guidance

> We can follow Kim, who has been the protagonist of the original deRSE Paper.

@CaptainSifff can you point me to the paper that is being referred to here, please?

**Comment by jngrad** [comment]
> ### other guidance
> 
> > We can follow Kim, who has been the protagonist of the original deRSE Paper.
> 
> @CaptainSifff can you point me to the paper that is being referred to here, please?

Anzt  *et al.* An environment for sustainable research software in Germany and beyond: current state, open challenges, and call for action [version 2; peer review: 2 approved]. *F1000Research* 9(295), 2021. [doi:10.12688/f1000research.23224.2](https://doi.org/10.12688/f1000research.23224.2)

**Comment by tobyhodges** [comment]
Thanks, @jngrad

**Comment by tobyhodges** [comment]
@CaptainSifff if possible please add a link to your introductory slides to line 17 of https://pad.gwdg.de/6zDMG7ldREOjPXXvpQhy5w

**Comment by CaptainSifff** [comment]
let's see if we can abuse here.....
[teaching-rse.pdf](https://github.com/CaptainSifff/paper_teaching-learning-RSE/files/12724130/teaching-rse.pdf)

**Comment by CaptainSifff** [comment]
we have succesfully finished the unconference.
