### ISSUE TITLE
Inclusion

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#137]
The current wording of competencies contains wording that is specific to the northern hemisphere. Fix this, make sure to reflect this in the values and probably also have a look at the other papers. Also notifying @ljgarcia

**Comment by mhagdorn** [comment]
looking for statistics I found from the [UNESCO Science Report](https://www.unesco.org/reports/science/2021/sites/default/files/medias/files/2022/01/Facts%20and%20figures%20from%20the%20UNESCO%20Science%20Report%202021.pdf):
 * women account for 33.3% of all researchers
 * [G20](https://en.wikipedia.org/wiki/G20) countries account for 88.8% of researchers

here I equate RSE with researchers.

**Comment by mhagdorn** [comment]
I have expanded the sentence by providing a little more context. @ljgarcia, do you want to add something?

https://github.com/CaptainSifff/paper_teaching-learning-RSE/tree/137-inclusion
