### ISSUE TITLE
RSE certificate for DFG

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#139]
The DFG has the notion, that applicants must have a "PhD or equivalent" to be eligible for funding.
It is REALLY important that we get some idea of this gap out there, such that future RSEs do not have to be forced to pursue a research path just in order to get a PhD and hence take on a leadership role.

**Comment by CaptainSifff** [comment]
Also see #108

**Comment by jpthiele** [comment]
Idea (somewhere in career path):
'Having spent a good amount of time as a junior RSE and with some finished projects to show for, XYZ was able to get a senior RSE certificate. This certificate is seen as an equivalent to a PhD when it comes to RSE specific grant applications by various funding agencies. Therefore, it allows XYZ to get funding for new projects in a senior RSE position.'

**Comment by CaptainSifff** [comment]
see #140

**Comment by hvwaldow** [comment]
TODOs:   
+ Find the actual rule in DFGs rules & regulations.
+ Find pertinent rules & regulations from other funding agencies.

**Comment by CaptainSifff** [comment]
hmm, but this would still require that they contribute to something scientific, I think. And they need to have actually an advisor from science.

**Comment by MakisH** [comment]
> The other question would be whether we should instead advocate for a cumulative PhD in RSE? This would not need any extra 'contracts' with funders and also maybe give the RSEs a better recognition in the scientific field.

This idea sounds interesting. As an RSE, maybe you contribute to multiple projects, which then also lead to publications. I could then imagine a cumulative PhD, which explains innovative RSE methods applied to enable each project. And each project would be in collaboration with domain scientists.

A technical problem, however, would be that graduate schools typically require that you are the first author in the publications you include in a cumulative thesis, which I assume RSE contributors are not going to be in a domain publication.

Such a cumulative PhD would be easier to acquire for someone working as a junior RSE in some (central) unit, compared to a traditional monograph.

**Comment by jpthiele** [comment]
> A technical problem, however, would be that graduate schools typically require that you are the first author in the publications you include in a cumulative thesis, which I assume RSE contributors are not going to be in a domain publication.
> 
Which could be solved by an RSE appropriate 'Promotionsordnung'
> Such a cumulative PhD would be easier to acquire for someone working as a junior RSE in some (central) unit, compared to a traditional monograph.
That was exactly the idea. To have a path for junior RSEs. 
As you might be able to graduate in a domain if you work as a domain RSE.

**Comment by CaptainSifff** [comment]
I've added some text to the career path. Now we have the science enabling doctor(which sounds more like an honorary PhD) and the traditional Dr-Ing.

**Comment by BeastyBlacksmith** [comment]
In [Research Software Engineer at the Netherlands eScience Center: Job Description](https://zenodo.org/records/7805870) they have the following requirement for senior RSEs:

> PhD or equivalent 4-6 years’ experience demonstrating independently generated research outcomes within a research or commercial organizatio

**Comment by ljgarcia** [comment]
In the career path, see https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/151, I also made a point about 2 years being probably too short to go from junior to senior.

**Comment by CaptainSifff** [comment]
One thing I'd like to consider is acceptance: Are you accepted without a PhD in an academic environment? That was one reason, why we went with doctor.
