### ISSUE TITLE
Example Career Path

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#140]
the discussion from the unconference #130 . Touches a bit on the issue in #139 .

**Comment by hvwaldow** [comment]
There is a new branch (example-career-path) which contains the text for this issue in one separate file:
https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/example-career-path/example_career_path.md

Currently its in really early stage but contains everything (a lot just verbatim) of the breakout session plus a last paragraph taken +/- from here: https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/139#issuecomment-1750144147
