### ISSUE TITLE
rename TEAM-skill or team-skills section

### ISSUE THREAD

**Issue by mschwarzmeier** [CaptainSifff/paper_teaching-learning-RSE#142]
Currently there is a skill TEAM within the subsection team-skills. To me that seems to be bad style.
The sub-section could be renamed to something like `social skills` or the TEAM-skill could be re-branded as `communication skills` and in that case stress that topic a bit more.

https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/d37e477d485417c55dae27751d3241c2fefec3d9/competencies.md?plain=1#L458-L476

**Comment by mschwarzmeier** [comment]
Also I had one or two more ideas:

> Working in a team is all about communication.
> For example RSEs need to be able to explain particular implementation choices made and may even need to defend them.
> This case of communication fosters mutual understanding, benefits the RSE for his/her teaching skills and
> represents a knowledge transfer from a RSE to domain scientists.
> The RSE in return can learn about where software concepts are not (yet) understood by the community
> or where the code fails to be clear for a domain scientist. _((e.g. new c++ standard or missing/bad documentation? (DOCBB)))_
> In another case, code reviews within a team of RSEs represent a knowledge transfer on an expert level
> and increase team cohesion.

and

> Senior RSEs may lead a team of RSEs.

Sounds like a leadership-skill (which would also be required to a RSE working in an interdisciplinary team, where he/she leads on the RSE topics). One could potentially stress the importance of communication in that case

**Comment by CaptainSifff** [comment]
Hmm, I get it.
 It reflects the notion, that RSEs create Software for Research in Teams....
And the wording is respectively chosen.

**Comment by mhagdorn** [comment]
I like the idea of renaming the section to _Communication Skills_.
