### ISSUE TITLE
Adapt Elixir Competencies to the appendix

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#15]

**Comment by samumantha** [comment]
As promised, I of course forgot what was exactly the idea here. Comparing our competencies to the Elexir ones in above link?

**Comment by CaptainSifff** [comment]
Hi Samantha, the idea was to have a look into their competencies and
1.) Figure out which competencies they  have are specific representations of ours
2.) What is really domain specific and therefore falls into the framework of $DOMAIN specialization.

**Comment by fer-rum** [comment]
Just for my understanding: Are we talking about the programming language?

**Comment by CaptainSifff** [comment]
Now, ELIXIR has already career paths and competencies here:
https://competency.ebi.ac.uk/framework/bioexcel/3.0/profiles/compare/10115/10117

So, it would be nice to work that in.

**Comment by CaptainSifff** [comment]
OK, looking at it, I probably meant more like their computational chemist specialaization:
https://competency.ebi.ac.uk/framework/bioexcel/3.0/profile/view/10115/alex-2
https://competency.ebi.ac.uk/framework/bioexcel/3.0/profile/view/10121/kim-0
since this fits to our description of the $domain-RSE

**Comment by tobyhodges** [comment]
The Mastery Rubric for Bioinformatics is also relevant to this: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0225256#sec008

**Comment by CaptainSifff** [comment]
Here we have another one: https://carcc.org/wp-content/uploads/2019/01/CI-Professionalization-Job-Families-and-Career-Guide.pdf

**Comment by CaptainSifff** [comment]
@jngrad has contributed some parts.

**Comment by jngrad** [comment]
@samumantha It has been split in separate files. You can find some of it in the last section "Bioinformatics skills and certification" in the appendix of `institutionalized_education.md`, and some more in the FAIR section of `survey.md`.

**Comment by CaptainSifff** [comment]
this is now in the appendix of the competencies.
The next step would be to check whether we need anything for the institutions.

**Comment by CaptainSifff** [comment]
now superseded by #126
