### ISSUE TITLE
proof-read example career path and try to attach it to the main text.

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#151]

**Comment by ljgarcia** [comment]
I had a look to this chapter. I had not read it before so it is a fully new look. I suggested some changes, see [PR 156](https://github.com/CaptainSifff/paper_teaching-learning-RSE/pull/156)
Some points to consider:

Line 12. In Kay’s world, some of the measures proposed in this paper have already been implemented.
I have observed that "measures" (for German speakers) does not always aligned with the regular meaning in English. Measure suggest me something that can be measured and I do not think we are proposing metrics in this paper.

Line 36. data set or dataset (all along the paper)

Line 37. notions (SWLC, RC) acronyms need to be expanded on the first use, same for OSI and JOSS in line 39, also line 47, 48

Line 44. "competitive IT salary" some will argue that academy does not offer competitive salaries (which is not always true)

Junior RSE sections. A period of two years seems short for all the mentioned activities. I am not sure if two years of experience are the regular time to move from junior to senior. That is not my experience as software developer but that experience was not in Germany.

**Comment by ljgarcia** [comment]
I would also like to discuss more about how to present the "Science Enabling Doctor".

Calling it "Doctor", saying that is another path to Dr.Ing, is kind of the same as saying that indeed a "Doctor" title is needed for RSE to become PIs and have the chance to apply for grants. I do not think this fully reflects what we have discuss. I think that what we want to stress is that there are other options in research to become a PI which do not require doing "Doctor" studies.

**Comment by CaptainSifff** [comment]
- timeframe has been changed.
- new name CRSP
- honorary doctorate optional
- added ref to DFG
- checked that the appendix is now mentioned multiple times.

Therefore closing this now.
