### ISSUE TITLE
Expand related work

### ISSUE THREAD

**Issue by jcohen02** [CaptainSifff/paper_teaching-learning-RSE#161]
Related work currently focuses on groups or organisations providing training materials and training activities.

There are also some groups working directly on competencies and learning pathways and I think there is some material here that should be included in related work. Some possible examples include:

 - HPC Certification Forum (https://www.hpc-certification.org/)
 - UNIVERSE-HPC (https://www.universe-hpc.ac.uk)
 - RSE Competencies Toolkit (https://github.com/RSEToolkit/rse-competencies-toolkit)
 - EMBL/EBI Competency Hub (https://competency.ebi.ac.uk/)
 - ELIXIR Competencies (re #15)

This is linked to #135.

**Comment by CaptainSifff** [comment]
Note Toby's notes:
https://pad.gwdg.de/gwkleozaTVOwWqcRuYxaSA

**Comment by CaptainSifff** [comment]
Closing this, since Jeremy has added a lot of the other initiatives.
