### ISSUE TITLE
Length and structure of the introduction

### ISSUE THREAD

**Issue by MakisH** [CaptainSifff/paper_teaching-learning-RSE#166]
The Introduction + Related Work is currently three pages, and the structure is a bit loose. If I were to put titles in each paragraph:

## Introduction

1. Computers are important **-> drop?**
2. Researchers need more and more computer skills that they don't learn in their studies
3. Researchers write software. RSE is a term.
4. RSE is a career.
5. RSEs are diverse but share core skills.
6. RSEs implement the FAIR principles for software
7. This paper identifies values and competencies
8. Terminology **-> Make a separate section after Introduction?**
   - Software
   - Research
   - Research Software Engineers (not explicitly)
9. Context / history of this paper
10. Outline (in several small paragraphs) **-> Merge and shorten**
11. Who may want to read this paper (a bit too long / loosely structured). **-> Shorten? Move?**

## Related work

Not really connected to the rest of the introduction/paper. Also brings in several citations that could probably be removed.

- Option A: Make it one short paragraph, cite one resource per example, and integrate it into the introduction.
- Option B: Drop it.

In both cases, I think a better place for this would be the follow-up paper on teaching.

## Action

If we agree on the general direction, I can try shortening this part and improving the structure.

**Comment by MakisH** [comment]
Check again the terminology about research / research software.

**Comment by CaptainSifff** [comment]
I guess this is closed now?
