### ISSUE TITLE
Citations as nouns

### ISSUE THREAD

**Issue by MakisH** [CaptainSifff/paper_teaching-learning-RSE#179]
I see that in many places, citations are used as nouns. For example:

> There are many software engineering curricula out there, that try to define
which tasks a software engineer should be able to perform. A recent example
highlighting some aspects in more detail than here is [@Landwehr2017].
The software skills outlined here are required to make research software adhere
to the FAIR principles. [@ChueHong2014] defines different levels of research
software reusability and the extent to which the software engineering skills
need to be applied to reach them.

Citation are then shown as numbers. I think this is strange (but a very minor detail). I like thinking in the Wikipedia citation style, where citations are colored superscripts, kind-of next to the text, instead of part of the sentences.

Instead, referring to the authors makes the sentences complete:

> A recent example highlighting some aspects in more detail than here is given by Landwehr et al. [@Landwehr2017].

**Comment by CaptainSifff** [comment]
so we need a decision here.

**Comment by jngrad** [comment]
@MakisH using `@Landwehr2017` instead of `[@Landwehr2017]` produces this:

> A recent example highlighting some aspects in more detail than here is Landwehr et al. [32].

Here is what pandoc does under-the-hood:
* `@Landwehr2017` :arrow_right: `\textcite{Landwehr2017}`
* `[@Landwehr2017]` :arrow_right: `\autocite{Landwehr2017}`
