### ISSUE TITLE
Author ordering, completeness, acknowledgements, affiliations

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#187]
@HeidiSeibold , @jlinx , @jpthiele , @jcohen02 @unode @samumantha , @jngrad , @fer-rum , @mhagdorn , @hvwaldow , @mschwarzmeier , @braunms , @BeastyBlacksmith , @tobyhodges , @knarrff , @dokempf , @ljgarcia , @fiveop 

We need to have some consent, over the author ordering.
Also make sure that your acknowledgements are up-to-date, and your affiliations.
And that you are in the author list!!!!!

**Comment by BeastyBlacksmith** [comment]
Actually I like the approach of [The Turing Way](https://the-turing-way.netlify.app/communication/aa/aa-equitable)

> The first author is always The Turing Way Community and then authors are listed in alphabetical order by last name.

Likewise we could put de-RSE as first author. But I don't have strong feelings about this either way

**Comment by CaptainSifff** [comment]
the de-RSE part happens when we submit it as position paper, which is a separate process. For the first thing we would need a name....

**Comment by jngrad** [comment]
There are several affiliations that only mention the university, without information about the institute or country: @mschwarzmeier @mhagdorn @fer-rum @unode @jpthiele @jcohen02 @jlinx @CaptainSifff

Alphabetical order would be fine by me, this is also how we did in the de-RSE position paper 001. As it stands, @unode would be the first author.

**Comment by braunms** [comment]
In order to emphasis different roles and ways of contribution, we could use [CRediT](https://credit.niso.org/).
Default contribution could be "Writing – original draft" and then additional roles can be assigned to each author, e.g "Supervision" for @CaptainSifff
I haven't used CRediT so far and I am not sure how we could include the roles in the authors list. Maybe in the footnotes where the email addresses might be placed usually?

**Comment by jpthiele** [comment]
> There are several affiliations that only mention the university, without information about the institute or country: @mschwarzmeier @mhagdorn @fer-rum @unode @jpthiele @jcohen02 @jlinx @CaptainSifff
> 
Good point, fixed and thereby checked mine!

**Comment by mschwarzmeier** [comment]
> There are several affiliations that only mention the university, without information about the institute or country: @mschwarzmeier @mhagdorn @fer-rum @unode @jpthiele @jcohen02 @jlinx @CaptainSifff

- [x] fixed my affiliation

**Comment by dokempf** [comment]
Added myself in #188. As my contribution is minimal, I am of course okay with being anywhere in the authors list. I would also support that those people that put a lot of effort in get mentioned more prominently, but that sort of requires a consensus on who that would be.

**Comment by jcohen02** [comment]
> There are several affiliations that only mention the university, without information about the institute or country: @mschwarzmeier @mhagdorn @fer-rum @unode @jpthiele @jcohen02 @jlinx @CaptainSifff

Likewise, fixed my affiliation (only added city/country so pushed directly to main to avoid opening another PR).

**Comment by CaptainSifff** [comment]
One thing(irrespective of the ordering discussion) I'd like to add to the discussion:
Since this is a community paper, everybody actually profits, the more people and institutions *represent* and stand behind this effort.

**Comment by HeidiSeibold** [comment]
I am fine with any ordering, but also would like it if the "first author" could be the "de-RSE community". Maybe @CaptainSifff as last author as you managed the paper writing. But really I have not been involved enough as of late to have a say. 😬

**Comment by MakisH** [comment]
As someone favored by the English alphabet, I would like it if I don't accidentally end up at a prominent place near the beginning. Some people contributed significantly more, and I would like to see those in the front as corresponding/equal contributors, while the rest of us can follow in, I guess, alphabetical order. I know that this is difficult to decide, but I hope that a benevolent dictator with good overview could make a suggestion.

I don't know how it works with having a community as an author, but it would be very nice to anyway have somewhere the term "community paper". It clarifies a lot.

**Comment by unode** [comment]
I reviewed my author information.

As for author order, whichever the community decides is fine by me. 
Also agree with having the **de-RSE community** as author and calling it a community paper.

Regardless, I suggest to be explicit about this somewhere in the text as there are different conventions and assumptions in different communities. Some memorable ones [include order of mushroom picking skills :mushroom:](https://twitter.com/khanaziz84/status/1465799352836755462?lang=en).
Perhaps there's a humorous one that can be used here (largest number of lines/characters of text/code deleted?)

**Comment by jngrad** [comment]
> Perhaps there's a humorous one that can be used here (largest number of lines/characters of text/code deleted?)

Since we plan on having the first author as "de-RSE", we could use a placeholder like the protagonist of our story (Kay) as a fictitious contributor (see [F. D. C. Willard](https://en.wikipedia.org/wiki/F._D._C._Willard)). The number of lines of text is fun too, although it could be hard to measure due to how much text was re-shuffled.

**Comment by CaptainSifff** [comment]
While the idea, of putting de-RSE as first author sounds nice, I don't think it is right for an arxiv upload on friday.
We can change that (The authors, and the ordering do not have to stay fixed for different versions of the paper), once we have published it to the de-RSE ML and gave people a possibility for feedback for some time. And it will get the RSE badge, once it goes through the de-RSE position paper process. But all of this comes later.

I agree with @MakisH that probably the abstract should already include the community aspect.

**Comment by tobyhodges** [comment]
If we cannot have de-RSE yet, I propose Florian as first author for the arxiv upload, with everyone else listed alphabetically afterwards. That will give us time to create a description of everyone's contributions according to CRediT (as proposed by @braunms above), to use when we are able to adjust the author list to add de-RSE as first author, while recognising @CaptainSifff's extraordinary contribution in the meantime.

**Comment by geyslein** [comment]
> One thing(irrespective of the ordering discussion) I'd like to add to the discussion: Since this is a community paper, everybody actually profits, the more people and institutions _represent_ and stand behind this effort.

Still, I feel a bit awkward to just add my name to competencies.md and contributors.yml since I did not make any commit. There are probably others out there who feel the same?! 

Thus, this is just to clearify. I just participated in the discussions at deRSE unconf and did some research on resources (#133) and masters programmes (#4).

If that's fine for you, I'd be happy to add my name to the list to strengthen the community (at least quantitatively :smile: )

**Comment by mschwarzmeier** [comment]
Any ordering will be fine with me.
Alphabetical upwards/downwards by n-th letter of first / last name, random, 'age' as years in academia, ordering of affiliations from north to south or west to east,...

**Comment by CaptainSifff** [comment]
in reply to @tobyhodges 
maybe it's just me feeling that it would be wrong to claim already now that we speak for all of de-RSE....

**Comment by CaptainSifff** [comment]
I've added @dokempf to the author list, assuming that he added himself to the contributors.yml file, but forgot to add himself to competencies.md

**Comment by dokempf** [comment]
> I've added @dokempf to the author list, assuming that he added himself to the contributors.yml file, but forgot to add himself to competencies.md

Ups, I had misclicked and added myself to `call_for_action.md` . I guess I am obliged to contribute to that one now.

**Comment by tobyhodges** [comment]
> maybe it's just me feeling that it would be wrong to claim already now that we speak for all of de-RSE....

No, I agree. I was suggesting that we list you @CaptainSifff as first author for now, and change that to de-RSE when we formally receive the blessing of the e.V.

**Comment by CaptainSifff** [comment]
resolved by e9d93cf96f840a8507968dd030539f7be6a578c0 for this publication. We remember to move this to de-RSE community once we get community blessing.
