### ISSUE TITLE
Acknowledgements level

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#193]
Hi all,
does someone see a way, to get the acknowledgements onto a heading level OUTSIDE of the appendix?, or right before the appendix, after Conclusion?
Thank You!

**Comment by jngrad** [comment]
I can have a look.

**Comment by MakisH** [comment]
The appendix is currently just a regular section, so maybe setting an `\appendix` before that would do the trick.

**Comment by jcohen02** [comment]
One simple fix is to make `Acknowledgements` a top-level heading by editing [L66 in `filter.py`](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/3590d423e65fbaf41f36270429950edb77cffda8/filter.py#L66) and removing one of the `#`'s. This results in the Acknowledgments being generated as Section 10.

**Comment by jngrad** [comment]
> One simple fix is to make `Acknowledgements` a top-level heading by editing [L66 in `filter.py`](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/3590d423e65fbaf41f36270429950edb77cffda8/filter.py#L66) and removing one of the `#`'s. This results in the Acknowledgments being generated as Section 10.

I've already edited the script to do that. I just need to edit all other Markdown files, because there the top-level uses `##` instead of `#`, then I can open the PR.

**Comment by jcohen02** [comment]
> I've already edited the script to do that. I just need to edit all other Markdown files, because there the top-level uses ## instead of #, then I can open the PR.

Is it necessary to edit everything else? That sounds like a lot of work - I simply made that edit and rebuilt and the PDF looks correct?

**Comment by jngrad** [comment]
> > I've already edited the script to do that. I just need to edit all other Markdown files, because there the top-level uses ## instead of #, then I can open the PR.
> 
> Is it necessary to edit everything else? That sounds like a lot of work - I simply made that edit and rebuilt and the PDF looks correct?

My new filter script extracts the `\appendix` to place the acknowledgements before the appendix chapters. But somehow `competencies.md` uses one level of hashtag instead of two, and now in all other documents the acknowledgements section becomes the first chapter... All the other documents needed editing anyway, because they currently use a phantom chapter 0.
