### ISSUE TITLE
build issue - too many authors

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#201]
I have build issues over here....
By removing some authors, the build works again.
I think LateX is running out of symbols for enumerating the authors.
This is the error message I get:

```
Missing character: There is no   (U+0020) in font [academicons.ttf]:!

! LaTeX Error: Counter too large.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.158 \begin
            {center}\rule{0.5\linewidth}{0.5pt}\end{center}
No pages of output.

```

**Comment by CaptainSifff** [comment]
@jngrad , @MakisH I would be grateful, to understand how we can solve that...

**Comment by MakisH** [comment]
I had faced something similar with footnotes, but there it was really using symbols: https://github.com/OpenFOAM-Journal/paperLatexTemplate/pull/10

Here, the list is using numbers...

**Comment by MakisH** [comment]
`U+0020` seems to be... whitespace?!? https://en.wikipedia.org/wiki/List_of_Unicode_characters#Basic_Latin

Maybe a specific author?

**Comment by jngrad** [comment]
The `U+0020` comes from academicons. They use a UTF-8 character from the reserved block (font-specific symbols) to display the icon, and a whitespace character sneaks in as a substitute. The actual issue here is that LaTeX can only have 9 footnotes per page (because there are only 9 special characters for footnotes, doesn't matter that we use numbers), or 15 with `footmisc`. Let me look into it.

**Comment by jngrad** [comment]
@CaptainSifff can you please share your PDF compile command? I cannot reproduce the error with XeLaTeX. Here is what `latexmk` does on my machine and in GitHub Actions:

```sh
xelatex -no-pdf -halt-on-error -shell-escape -recorder --jobname="competencies"  "competencies.tex"
```

**Comment by MakisH** [comment]
Also works locally on my machine, with the default `make` target.
TeX Live 2021 on Ubuntu 22.04.

**Comment by CaptainSifff** [comment]
Running 'xelatex -no-pdf -halt-on-error -shell-escape -recorder --jobname="competencies"  "competencies.tex"'
------------
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023/Arch Linux) (preloaded format=xelatex)
 \write18 enabled.

**Comment by jngrad** [comment]
The main branch now uses pdflatex instead of XeLaTeX, author affiliations via `authblk` instead of footnotes, and `orcidlink` instead of `academicons`. Don't forget to delete your build folder before attempting to run the new Makefile.

**Comment by CaptainSifff** [comment]
Works! Thank You!
