### ISSUE TITLE
Only Machine Learning in competencies

### ISSUE THREAD

**Issue by ljgarcia** [CaptainSifff/paper_teaching-learning-RSE#206]
Only machine learning is considered under "Machine learning (ML) - RSE". 

Some people make a clear distinction between machine and deep learning, some others use them as kind of the same. How can we make sure both are understood from the text? Do we need to change it to "Artificial Intelligence - RSE"? Reinforcement learning is commonly another category...

**Comment by jpthiele** [comment]
Talking about ML and AI they are more distinctive at least in proper SE terms than ML and deep learning.

**Comment by ljgarcia** [comment]
Discussed today in the meeting. We will keep the title as it is and add a note in the corresponding text about it also including deep and reinforcement and similar
