### ISSUE TITLE
Provide alternative options for call?

### ISSUE THREAD

**Issue by sdruskat** [CaptainSifff/paper_teaching-learning-RSE#225]
I've tried to make the paper call for the last two or three weeks, but was unable to do so due to caretaking responsibilities.
Is there another option for joining the discussion more actively? A second date for a call? Alternating weeks over an alternative date/time?
(I think this may also be interesting for members of the community who want to make co-authorship but cannot meet the required regular participation.)

Not urgent to solve, unless you plan on meeting over the holidays ;).

Happy end of year 🌟!

**Comment by CaptainSifff** [comment]
How about a poll starting in January?

**Comment by CaptainSifff** [comment]
And here's the poll:
https://terminplaner6.dfn.de/en/p/a2ac3bc0d23f715b165ab443c9399d94-546968

Note that I expect we have to reschedule again after deRSE24. also due to the start of the new semester.

**Comment by MakisH** [comment]
General comment, since now is the scheduling: I notice that often the meetings at the current timeslot run for around two hours or even open-ended. Zoom-ing for 2h or more every week is a bit exhausting and leaves less time for actual action. I think it would be beneficial to restrict ourselves to the proposed 1h per slot.

**Comment by CaptainSifff** [comment]
Also notifying people over here:
Meeting Notes:
https://pad.gwdg.de/s/pVBQ3Sh7Z

**Comment by MakisH** [comment]
> General comment, since now is the scheduling: I notice that often the meetings at the current timeslot run for around two hours or even open-ended. Zoom-ing for 2h or more every week is a bit exhausting and leaves less time for actual action. I think it would be beneficial to restrict ourselves to the proposed 1h per slot.

Follow-up, as we now had a 1h meeting: I used the extra time to already do most of what I had to do for the next meeting, as I still had energy and time! :smile: I think we can do it and it will help us a lot :hugs:

**Comment by CaptainSifff** [comment]
Closing this, since we now have:

- a new date
- notes
- and hopefully, soon a mailing list.

And we need to tidy up the issue list....

**Comment by CaptainSifff** [comment]
So we now have a mailing-list: https://lists.uni-wuerzburg.de/mailman/listinfo/teachingrse
