### ISSUE TITLE
License -> CC-BY V4 

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#233]
All our content should have a license. our arxiv paper is licensed as CC-BY V4. In the spirit of making it as easy as possible for other's to reuse our material, so that our goals are futhered, I think we should also apply this license to the content of our repository.

**Comment by mhagdorn** [comment]
yup, agree very much with that

**Comment by jlinx** [comment]
also agreement from my side
