### ISSUE TITLE
Curiosity: Is it really a skill? We need a better term.

### ISSUE THREAD

**Issue by MakisH** [CaptainSifff/paper_teaching-learning-RSE#235]
During today's meeting, and while looking at #203, we got confused whether it really makes sense to name the "NEW" skill as "Curiosity" and whether this is really a skill or a value.

Similarly, when looking for resources for each pillar (https://github.com/DE-RSE/survey_rse_training/issues/2), I noticed that I could not map anything to this skill. How can it be learned?

Current phrasing:

> RSEs gain their reputation from their effectiveness in interacting with their domain peers. Therefore, some
curiosity together with a broad overview of the research field is required as this enables the RSE to learn new
methods and algorithms directly from domain peers. Curiosity is also reflected when an RSE is actively trying out
new tools. Lifelong learning is then no longer just a phrase but becomes a motivation to work.

**Comment by MakisH** [comment]
Following up on @sdruskat's point, I think the key here is in the

> a broad overview of the research field is required as this enables the RSE to learn new
methods and algorithms directly from domain peers.

We then need something like "navigating the literature", "evaluating new resources/methods". This would then connect with the next point of "Understanding the research cycle".

The rest of the paragraph is mostly about curiosity.

**Comment by guadabsb15** [comment]
Maybe a way of summarizing it could be "actively keeping up to date" or "actively keeping current" ... just some thoughts

**Comment by CaptainSifff** [comment]
I feel we should be careful here and be aware of the ramifications. Making "Curiosity" a prime competence makes it easy to argue that RSE are qualified to do research, and hence should have the same pay and other statuses.

**Comment by MakisH** [comment]
There is no doubt that we want to have curiosity and the ability to perform and lead research as characteristics of RSEs. The only question is how we name/present it: we may need to refine it.

I repeat my question: _How can it be learned?_
Can I teach myself to be curious, or is it a personality trait that I either have it or not?
I cannot just decide to be curious, I assume.

**Comment by mhagdorn** [comment]
I guess _curiosity_ is a trait, that if you have it helps a lot. The bit that can be trained/fostered is to make sure to have time for training and research.

**Comment by CaptainSifff** [comment]
hmm yes, you don't start a STEM degree, if you consider tax accounting attractive....

**Comment by fer-rum** [comment]
You may want to check out this article with relation to learned curiosity: https://www.teachthought.com/learning/curiosity-in-learning/

**Comment by mschwarzmeier** [comment]
> I feel we should be careful here and be aware of the ramifications. Making "Curiosity" a prime competence makes it easy to argue that RSE are qualified to do research, and hence should have the same pay and other statuses.

I like to believe RSEs are qualified to do research. They might not be as specialized as a pure domain scientist.

**Comment by MakisH** [comment]
This was meant to be a pedantic comment about phrasing, which still triggers the question _"how can it be learned, so that we can teach it?"_. Could still trigger (or rather continue) an interesting discussion, but we don't need it urgently.

**Comment by jlinx** [comment]
If it is not a skill, it could be a mindset. In this case "Curiosity" could also be translated to the willingness for "Lifelong learning" in this fast-moving environment.

**Comment by jpthiele** [comment]
Rough idea from Dagstuhl: 
(skill) adaptivity and lifelong learning.

**Comment by jpthiele** [comment]
And something about professional development to share the responsibility between employer and employee.

**Comment by jpthiele** [comment]
After searching a bit the german term is certainly 'Anpassungsfähigkeit'

**Comment by mhagdorn** [comment]
hmm, I never liked the terms _adaptivity_ or _Anpassungsfähigkeit_. To me they suggest that the individual has to change as a response to whatever comes from the outside. Curiosity and life-long learning leave agency with the individual. I can see that this might be a little naive but I don't think we need to further strengthen the idea that we must fit into whatever role we are assigned to.

**Comment by michelemartone** [comment]
Relating to the glossary section: the word "curiosity" refers to a trait of people apt to conduct research, I'd never refer to it to a skill as such.
Sure, curiosity can be transitory (it can come and go) and its daily related practices can be honed and learned with a number of related skills.

That said, I don't have yet a ready replacement suggestion for the NEW skills, which IMHO too would need a revision.
I subscribe's @mhagdorn 's concerns about preserving agency (not present in _Anpassungsfähigkeit_) and @jpthiele 's wrt the fact that the scientific employer has a responsibility in allowing some free room for development.

**Comment by mschwarzmeier** [comment]
Some re-phrasings:
-  intellectual curiosity
-  inquisitiveness
-  eagerness for knowledge
-  thirst for knowledge

To pick up, what @jlinx said:
> If it is not a skill, it could be a mindset.

and to answer the question of @MakisH : yes, then I would argue, it can be trained (maybe up to a certain extent). This makes it similar to a skill set.

---

**To be successful at curiosity**, if you have it, you need to be clever, have a quick & open mind, good grasp/apprehension, some fantasy,..., but the central skill seems **quick learning** (sometimes independent/sometimes working together)

**Comment by MakisH** [comment]
I will prepare an rewrite, based on "Ability to conduct and lead research". In this, I will also mention curiosity and lifelong learning, while referring to resources for learning how to do research, and mention that RSEs often (but not necessarily) already have a PhD.

**Comment by sdruskat** [comment]
> RSEs often (but not necessarily) already have a PhD.

Sure you've seen the Intl Survey results ([< 40% have a PhD](https://softwaresaved.github.io/international-survey-2022/country/world/#education-and-academic-field)).

**Comment by MakisH** [comment]
> > RSEs often (but not necessarily) already have a PhD.
> 
> Sure you've seen the Intl Survey results ([< 40% have a PhD](https://softwaresaved.github.io/international-survey-2022/country/world/#education-and-academic-field)).

No, I did not know about this resource, thanks for sharing!
