### ISSUE TITLE
Naming / Logo

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#240]
So, I checked previous notes and notes from the unconference, talked to @jlinx whether sth. is already known, and it turned out, that is not the case. So we can come with something of our own!

**Comment by CaptainSifff** [comment]
Sparked by the Logo-issue over here: https://github.com/DE-RSE/survey_rse_training/issues/8
I came across a couple of things:
- RSE-edu
- edu-RSE
- de-RSE-edu  (claim we are Germany specific)
- edu-de-RSE  (URL like specializations...)

and then we can combine this either with "Arbeitskreis", "workgroup", "Special Interest Group", "Project",...
My vote today would go to sth. sounding international( We have @jcohen02  ) and sth. like project, or workgroup.

e.g. 

edu-RSE project

this is a bit better since education is a bit more than teaching(current name of the Mailing List) and thereby encompasses everything that we are trying to formulate.

**Comment by CaptainSifff** [comment]
notifying @jpthiele , @hvwaldow , @jlinx , @knarrff , @MakisH for opinions.

**Comment by CaptainSifff** [comment]
The other possibility would be, what we currently have:
- the teachingRSE project.

**Comment by jpthiele** [comment]
I kind of like 'the teachingRSE project'

**Comment by jlinx** [comment]
My feeling is that "teaching" is a subset of "education". Although I like the name "the teachingRSE project" because it sounds a little more pro-active/dynamic. In the end it is "just" a name and we can do more than the name implies. Do we?

**Comment by mhagdorn** [comment]
I don't like edu so much as that to me sounds like an American domain name. So my vote goes to the "teachingRSE project"

**Comment by jcohen02** [comment]
I also rather like "teachingRSE" so I think it's a 👍 from me for that too 🙂

**Comment by MakisH** [comment]
I like the `*edu*` and `*teaching*` names equally.

For the survey website, I currently set the URL as `learn-and-teach`, as teaching itself is not enough for the two perspectives. In that sense, an `*edu*` name would help with concision, logo, URL, etc. We are dealing with "RSE education" in general (teach, learn, plan, structure, ...). Any variation of that is fine.

So far I have always been thinking of this group in terms of "teaching RSE", so I recognize the familiarity bias.

And yes, of course, it is just a name, and both name option tracks are clear.

**Comment by hvwaldow** [comment]
I agree with what I believe is consensus: "edu.." would be semantically a tad more to the point, yet, "teachingRSE" sounds better, more succinct, and still evokes the right idea.

**Comment by MakisH** [comment]
I suggest the following:

- Name: `teachingRSE` - We are already using that, it is clear
- Logo: `deRSE` logo with `teaching` on the right - The [chapters](https://de-rse.org/chapter/) logo also has a full word.
- URL for the survey website: `learn-and-teach` - Descriptive and memorable

**Comment by CaptainSifff** [comment]
Also over here,
the link to the vote: https://terminplaner4.dfn.de/pdw9KaU1kEwCvWMZ

**Comment by CaptainSifff** [comment]
So, then it's teachingRSE project. I will update repos, and the abstract for deRSE24. @jlinx , @knarrff this is our Arbeitskreis name for the future.
