### ISSUE TITLE
RSE tasks and responsiblities section

### ISSUE THREAD

**Issue by annalenalamprecht** [CaptainSifff/paper_teaching-learning-RSE#241]
I need to start a discussion about (current) Section 4.4 RSE tasks and responsibilities in the competencies paper. 
The responsibilities are also in the title of the paper, so I was expecting to get to a major point here after the competencies. 
However, the section turns out to be mainly a recollection of things that RSEs said they would have liked to have learnt. Super interesting in itself, but it is just a bit about tasks and more about competencies again.

I am unsure what the best alternative would be, but here are some ideas to discuss:
- Turn it into an actual "Tasks and responsibilities" section, but that would need additional content.
- Use the "what would I have liked to have learnt" records as a motivation for the skills presented in 4.1-4.3
- Integrate a description of the tasks into the introduction (where RSEs are introduced)
- Put the answers from the workshop into some sort of appendix for reference.

**Comment by CaptainSifff** [comment]
It could also be a place to bring in version control and source code repositories.

**Comment by mhagdorn** [comment]
> It could also be a place to bring in version control and source code repositories.

I think that's a good idea

**Comment by CaptainSifff** [comment]
maybe related: issue #58
