### ISSUE TITLE
Think about SRU

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#249]
As a follow-up to #242 :
Software Re-Use (SRU) is listed as a research skill, but it is actually one of the classical key SE/technical skill. Also its description is mainly technical and not very research-specific, so I wonder if it should be moved to the technical skills?

**Comment by CaptainSifff** [comment]
Notifying @annalenalamprecht

**Comment by CaptainSifff** [comment]
phrase it towards research. Possible items:
- conflict between efficient reuse and competing implementations for re-use.
- conflicts between science funders and researchers, implementors.
- better documenting reuse? reproducibility?
- abundance of prototype stage software?

**Comment by MakisH** [comment]
"abundance of prototype stage software": A term I really liked here from the discussion was the "EDA (exploratory data analysis)". The emphasis is on the exploration: You are putting together rough tools to do some research, but without even thinking that these tools would ever be reused even by yourself.

Interesting concept as well (suggested by @jngrad): [https://de.wikipedia.org/wiki/Bananenprinzip](https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/zoom_custom_url=1&zoom_im_wrapper_url=1&originalUrl=https://de.wikipedia.org/wiki/Bananenprinzip&isInsertLink=0&originalText=https://de.wikipedia.org/wiki/Bananenprinzip&seq=8) (English page: https://en.wikipedia.org/wiki/Perpetual_beta)

**Comment by CaptainSifff** [comment]
Re-Use has a consumer side-> We address this in technical skills.
Here it is about the consumer side, being researchers.

**Comment by hvwaldow** [comment]
I tried to bend that more towards "Research Skills": #254.
