### ISSUE TITLE
Add notion of research integrity into research lifecycle

### ISSUE THREAD

**Issue by jpthiele** [CaptainSifff/paper_teaching-learning-RSE#261]
Again about awareness,
we should add an awareness of research ethics 
and integrity as part of the research lifecycle.

**Comment by CaptainSifff** [comment]
isn't this in the fundamental values section?

**Comment by jpthiele** [comment]
This was my initial reaction as well, but yes and no.
We did consider the ethics of our work. 
However, this does not include research projects in specific fields (e.g. biomedical) 
which need written approval. 
At least awareness that this may be needed in the overall cycle is then very much part of RC.

**Comment by mhagdorn** [comment]
I would have thought that ethics approval is something the PI needs to sort out.

**Comment by jpthiele** [comment]
Yes, hopefully. But you need awareness that this can be part of the process. 
So a half sentence on that would be the idea. I can draft a few things on the issues raised until next weeks meeting.

**Comment by CaptainSifff** [comment]
probably related: #266
