### ISSUE TITLE
Competency: Debugging

### ISSUE THREAD

**Issue by jpthiele** [CaptainSifff/paper_teaching-learning-RSE#3]
In my "experienced RSEs" group one skill almost everyone wished for was debugging. I'm not sure whether this really fits in core competencies or if there should be a broader competency of SE skills where this fits into.

**Comment by CaptainSifff** [comment]
This is now partially addressed by the short competency: "Software Behaviour and analysis" ....

**Comment by CaptainSifff** [comment]
Closing this, since we have discussed this a lot and it went into the "Software behaviour and analysis" competency.
