### ISSUE TITLE
work in the DLR classification

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#38]
The DLR has a nice classification of software and the level of seriousness that entails:
https://elib.dlr.de/121502/
We should find some spots in our paper to hint at that.

**Comment by jngrad** [comment]
A similar classification can be found in ref `ChueHong2014`: Neil Chue Hong, Minimal information for reusable scientific software, 2<sup>nd</sup> Workshop on Sustainable Software for Science: Practice and Experiences. [doi:10.6084/m9.figshare.1112528](https://doi.org/10.6084/m9.figshare.1112528), with different grades per criterion. It is however more focused on software quality than RSE skills.

**Comment by jngrad** [comment]
There is the [EMBL-EBI Competency Hub](https://competency.ebi.ac.uk/), e.g. [BioExcel 3.0 / Competencies](https://competency.ebi.ac.uk/framework/bioexcel/3.0/profiles/compare/10115/10117), that focuses more on RSE skills.

**Comment by CaptainSifff** [comment]
classification could entail that you need more senior personel

**Comment by CaptainSifff** [comment]
Probably best in SWLC.

**Comment by mhagdorn** [comment]
I will look into this
