### ISSUE TITLE
General: Masters Programme

### ISSUE THREAD

**Issue by jpthiele** [CaptainSifff/paper_teaching-learning-RSE#4]
I think a core challenge would be to open this to SEs as local domain lecturers would have to be open to teach them some domain. Nevertheless, there are good master's courses aimed at different groups already.

One example from Hannover is the wind energy engineering master where some courses are for everyone and some courses are depending on the Bachelor degree of the students and aimed at teaching civil engineers some of the mechanical and electrical engineering skills needed and vice versa.

But of course a curriculum for domain Bachelors to learn SE skills is somewhat easier to design.

**Comment by fer-rum** [comment]
The TU Dresden offers a masters course in [Computational Modelling and Simulation](https://tu-dresden.de/studium/vor-dem-studium/studienangebot/sins/sins_studiengang?autoid=29461&set_language=en) which is very RSE heavy without ever explicitly mentioning it.

**Comment by mmesiti** [comment]
Adding also here that at ICTP/SISSA in Trieste (Italy) they have been offering a "Master in HPC"  since 2014 https://www.mhpc.it/modules-0

**Comment by mhagdorn** [comment]
also HPC master programmes at EPCC Edinburgh: https://www.epcc.ed.ac.uk/education-and-training/masters-programmes

**Comment by MakisH** [comment]
At the Technical University of Munich, we have a [M.Sc. Computational Science and Engineering](https://www.cit.tum.de/cit/studium/studiengaenge/master-computational-science-engineering/), which admits students from any kind of STEM field (with some programming and math experience), and teaches numerical programming, various programming skills (with some focus on HPC), and includes elective modules in methods (e.g., machine learning) and application areas (e.g., fluid dynamics). In recent years, we have put a lot of effort in adding some RSE skills in the (new) 1-week onboarding course "CSE Primer" (Linux, Git, working in teams, Matlab, C++, plus some project), in the first-semester "Advanced Programming" (C++ with building, testing, packaging, collaborative mini-project, ...), and in practical courses, such as the "Computational Fluid Dynamics Lab" (larger simulation-focused team project).

**Comment by dokempf** [comment]
Heidelberg University has a [MSc Scientific Computing program](https://www.uni-heidelberg.de/de/studium/alle-studienfaecher/scientific-computing/scientific-computing-master) that, although not explicitely and not using that terminology, produces RSE candidates.

**Comment by geyslein** [comment]
The ['Hochschulkompass'](https://www.hochschulkompass.de/studium/studiengangsuche/erweiterte-studiengangsuche.html) of the HRK lists several programs about computing in science/scientific computing:
- Computing in Science (U Hamburg): https://www.uni-hamburg.de/campuscenter/studienangebot/studiengang.html?1239877544
- Data Science & Scientific Computing (H München): https://www.cs.hm.edu/studienangebote/studiengaenge/id_data_science/index.de.html
- Scientific Computing (U Bayreuth): https://www.scientific-computing.uni-bayreuth.de/en/index.html
- Scientific Computing (TU Berlin): https://www.tu.berlin/go1036/s62/
- the one already mentioned by @dokempf 
- Computational Science and Engineering (U Ulm): https://www.uni-ulm.de/mawi/mathematik-und-wirtschaftswissenschaften/studium-und-lehre/studiengaenge-master/m-sc-computational-science-and-engineering/
- Research in Computer and Systems Engineering (TU Ilmenau): https://www.tu-ilmenau.de/studium/vor-dem-studium/studienangebot/masterstudiengaenge/research-in-computer-systems-engineering-m-sc

There are quite a many programs on [computational science(s)](https://www.hochschulkompass.de/studium/studiengangsuche/erweiterte-studiengangsuche.html?tx_szhrksearch_pi1%5Bsearch%5D=1&tx_szhrksearch_pi1%5Bstudtyp%5D=3&tx_szhrksearch_pi1%5BQUICK%5D=1&tx_szhrksearch_pi1%5Bfach%5D=computational+science) as well, however imho these are often the successors of formerly known programs as Bio/Geo/... Informatics and the likes (I suppose that's too little RSEish?!).

**Comment by MakisH** [comment]
Closed by #189, maybe start new PRs to that file (which will eventually be moved to a webpage) in case there are more.
