### ISSUE TITLE
Put more emphasis on importance of documentation

### ISSUE THREAD

**Issue by tobyhodges** [CaptainSifff/paper_teaching-learning-RSE#58]
[The description of the _Creating documented code building blocks_ (DOCBB) skill](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/paper_teaching-learning-RSE.md#creating-documented-code-building-blocks-docbb) makes mention of documentation, but I think it is also relevant to several of the other skills (_Outside Party interaction (USERS)_; _Teaching (TEACH)_; arguably also _Working in a team (TEAM)_). 

In particular, documentation should exist in different forms and for different audiences - I like [the Diátaxis framework](https://diataxis.fr/) (_"The Grand Unified Theory of Documentation"_, no less!), which describes documentation as divided into of four categories based broadly on the audience and function of the content: Tutorial, How-To Guide, Reference, and Explanation. I think it is desirable for an RSE to be able to produce all of these types of documentation for their research software, and to understand the need for each kind for users in different contexts.

Is there room in the paper to stress/expand a little on the importance of documentation for research software, e.g. by mentioning it specifically in the different skill categories?

**Comment by CaptainSifff** [comment]
I certainly get, that documentation is important. But of course we should not have a paper on how to write good documentation. We should maybe not forget, that there are very likely ISO Standards for technical documentation and some domains need to follow that, too. Which makes the kind of documentation a bit of domain specific and is probably a choice for implementors in their curriculum. I do like the idea of mentioning documentation

**Comment by jpthiele** [comment]
But I think the diataxis framework is worth mentioning together with their basic idea that different stages/dimensions, i.e. learning vs. working and practical vs. theoretical, require different types of documentation.
So I would say a short two to three sentences would offer a benefit in the DOCBB skill.

**Comment by CaptainSifff** [comment]
Hi @tobyhodges , @jpthiele Any interest in reviving this for a discussion?
