### ISSUE TITLE
Another argument for dedicated RSE education

### ISSUE THREAD

**Issue by braunms** [CaptainSifff/paper_teaching-learning-RSE#60]
In addition to the estimated required number of RSEs #23, another reason is the number of increasing vacancies for RSEs or people with related skills. E.g.: We could evaluate statistics of de-RSE mailing list history. Could we somehow extrapolate the demand for RSEs from this number as well?

**Comment by CaptainSifff** [comment]
hm, so you argue, that if there are x job openings per year on the ML, then we need to produce x amount of graduates?

**Comment by braunms** [comment]
It filtered all [de-RSE] emails for "job", "stellenausschreibung", "position", "vacancy" and removed any replies. I simply added up the number of the positions over time, starting with May, 2021. I applied a 2nd degree polynomial extrapolation to estimate a possible tendency (during the summer there always seems to be a dent).

![rse-job-emails](https://github.com/CaptainSifff/paper_teaching-learning-RSE/assets/30432154/e1163051-da75-4e18-b5a9-dfa4691b82c4)

![rse-job-emails_extrapolation](https://github.com/CaptainSifff/paper_teaching-learning-RSE/assets/30432154/62c8b028-2f3e-42ee-b378-cf9c65b266bb)

I suspect that it is hardly possible to derive a specific number of required RSEs from that. But the trend of increasing vacancies could be a complementary reason, why RSEs need to be explicitly trained to meet future demand...

**Comment by braunms** [comment]
In order to argue that additional trained RSEs are needed, we should also know whether or not all vacancies can be filled within a certain period of time.

I am closing the topic for now, as this will not lead to any actionable findings...

**Comment by CaptainSifff** [comment]
Great work nonetheless!!
