### ISSUE TITLE
Ethics

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#68]

**Comment by CaptainSifff** [comment]
Also @mhagdorn

**Comment by CaptainSifff** [comment]
mention GDPR.

**Comment by CaptainSifff** [comment]
include data protection, anonimty, ethical considerations, DLR paper has resources.

**Comment by mhagdorn** [comment]
Software Engineering Code of Ethics

https://dl.acm.org/doi/abs/10.1145/317665.317682

**Comment by mhagdorn** [comment]
this should also be mentioned in the teaching RSE section

**Comment by mhagdorn** [comment]
Currently the *Legal aspects (LEG)* skill only contains licensing considerations and possibly copyright/patent issues. Another aspect that is totally missing is compliance with regulatory frameworks, eg GDPR and accessibility. I am kind of reluctant to lump ethics into this skill as well since ethics/moral values are specifically not legal aspects. Maybe call it *Software and Society* or something like that? The questions the RSE would need to ask are 
 * how is my software licensed? can it be reused, etc - FAIR aspects
 * do I violate patents/copyright of others?
 * do I need to consider particular laws/regulatory frameworks? GDPR, accessibility, etc
 * how does my software interact with society in general? Does it serve the Public?

**Comment by jngrad** [comment]
Further ethics resources:
* Alidoosti *et al.* Incorporating Ethical Values into Software Architecture Design Practices, Proceedings of the 2022 IEEE 19<sup>th</sup> International Conference on Software Architecture Companion (ICSA-C), IEEE, 2022, [doi:10.1109/icsa-c54293.2022.00031](https://doi.org/10.1109/icsa-c54293.2022.00031)
* Tavani, *Ethics & Technology: Controversies, Questions, and Strategies for Ethical Computing*, 4th edition, 2012, John Wiley & Sons, ISBN: 978-1-118-28172-7
* Himma et Tavani (Eds.) *The Handbook of Information and Computer Ethics*, 2008, John Wiley & Sons, ISBN: 978-0-471-79959-7

GDPR and cybersecurity:
* Dimitrov, Konstantinopoulou, Nisheva, [Best Practices for GDPR, Data Interoperability and Cybersecurity](https://www.eurocc-access.eu/wp-content/uploads/2022/09/BestPractices_DataManagement_v1.0.pdf), White paper, EuroCC, 2022
* Codecov team, [Bash Uploader Security Update](https://about.codecov.io/security-update/), April 2021: the tool used by open source software developers to consolidate and report code coverage information was compromised, leading to a security breach in self-hosted continuous integration servers.
* Krause, [Cyberattack against Supercomputers](https://www.john-von-neumann-institut.de/en/news/announcements/2020/2020-06-cyberattack-e), JSC News No. 273, June 2020: multiple supercomputers and a federal cluster in Germany were the target of a cyberattack. Several systems had to remain offline for weeks. These facilities now require two-factor authentication.
* [District Court Munich I, judgment of 01/20/2022, file number: 3 O 17493/20](https://dejure.org/dienste/vernetzung/rechtsprechung?Gericht=LG%20M%FCnchen%20I&Datum=20.01.2022&Aktenzeichen=3%20O%2017493/20): an unnamed website operator used the Lato font on their website, which is automatically downloaded from Google servers by web browsers that didn't cache it, thus exposing the visitor IP address. Some web content management systems have this font as a default setting (and replacing it with a different font can require installing a plugin). The automatic download takes place before any consent form can be processed, which is an issue under the GDPR. The fine was 100 Euros.

**Comment by CaptainSifff** [comment]
hmm, OK, GDPR, accessibility, patents, ... is definitely part of the (LEG) skill. This is supposed to contain the interaction of software with established jurisdictional frameworks. But you come to the interesting point that we currently have no explicit reflection about the artifacts we are creating and their ethical evaluation. And we have to cover that base at up-to three fronts. Ethics of Software Artifacts. What is ethics of the research I'm doing or I'm supporting? Are the team processes that I'm proposing or that I'm part of. We already tried to touch upon certain aspects by emphasizing the openness of research and the review process. I wonder whether we could put these notions into some kind of preamble for the competencies? Or a separate value section?

**Comment by mhagdorn** [comment]
I think this would fit nicely into the introduction to the skill section since those values should guide all the skills

**Comment by hvwaldow** [comment]
> Currently the _Legal aspects (LEG)_ skill only contains licensing considerations and possibly copyright/patent issues. Another aspect that is totally missing is compliance with regulatory frameworks, eg GDPR and accessibility. I am kind of reluctant to lump ethics into this skill as well since ethics/moral values are specifically not legal aspects. Maybe call it _Software and Society_ or something like that? The questions the RSE would need to ask are
> 
>     * how is my software licensed? can it be reused, etc - FAIR aspects
> 
>     * do I violate patents/copyright of others?
> 
>     * do I need to consider particular laws/regulatory frameworks? GDPR, accessibility, etc
> 
>     * how does my software interact with society in general? Does it serve the Public?

The first point is more like part of "best-practices". The usual development-mode in research.

2 and 3 are LEG

I think only the fourth point is somehow suited for a separate "Ethics" text-unit. I think GDPR can also be mentioned there (next to its mentioning in LEG) because is is the legal implementation of an ethical idea.

**Comment by CaptainSifff** [comment]
by @jcohen02 I guess the other “general” ethical aspect (diversity was mentioned a couple of times earlier in the discussion) is ensuring that you help to underpin diversity and good ethical practices in the way you treat colleagues, collaborators and people more generally in the context of the work that you do - the people aspect of ethics.

**Comment by braunms** [comment]
Some more thoughts:

- Ethics best practices on a personal level: [The Carpentries Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#the-carpentries-code-of-conduct)](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)

- Another LEG topic: (Export control at universities)[https://www.beschaeftigte.uni-stuttgart.de/en/research/export-control/]

Ethics in short?:
RSEs have to consider the possible consequences the usage of research software they are involved in could have on other people.
They should no be involved in (and actively prevent?) development of research software that could be used to harm people in any way.
Would we have to define what we mean with 'harm'? ( https://www.heise.de/news/Australien-Sozialhilfe-Algorithmus-fuehrte-zu-Suiziden-und-verschaerfte-Armut-9210590.html )

**Comment by mschwarzmeier** [comment]
I am torn.
On one side software is a tool. You can use a hammer to build a house or you can hurt people. There are much more powerful tools on construction sites than hammers. Therefore, if you are building anything that a RSE typically is working with, you are just providing tools (simulation, optimization,... software).
Nobody would&should blame some simulation software vendor, if that simulation software is used for bad purposes. The software most likely is designed to be general purpose.

On the other side with a flip in a NN to seek toxicity instead to avoid it, a medical drug search becomes a deadliest-nerve-agents-search, run in 6h on a rather normal PC.
Urbina, F., Lentzos, F., Invernizzi, C. et al. Dual use of artificial-intelligence-powered drug discovery. Nat Mach Intell 4, 189–191 (2022). https://doi.org/10.1038/s42256-022-00465-9

**Comment by braunms** [comment]
I guess, there would be no way at all that authors could prevent others to misuse their open source research software. But when talking about ethics in RSE, we imply that RSEs actually can do something to at least limit possible misuse.  Therefore, to a certain extent, they could be held responsible for misuse.

The big question might be: What can or should RSEs actually do and what would be sufficient to be cleared of being responsible for misuse of their software?

A workflow could be look like:
- Think of "easy ways", how your software could be changed or how the purpose could be "inverted" in order allow misuse.
- Are there measures that can prevent those changes?
- If there are no ways to prevent those changes, one solution would be not to publish the software or only publish harmless parts of it(?)

Analogous to the [Data Protection Impact Assessment](https://gdpr.eu/data-protection-impact-assessment-template/) in the future there could be something like a "Research Software Impact Assessment"?

**Comment by jcohen02** [comment]
This is a really useful discussion and there are some great resources in this issue (yet another paper, perhaps 🤔 - we must be up to about 4 additional papers now! 😆). Ethics is, of course, a hugely important issue. However, I feel this is an entire research field in its own right. In the context of this paper, I think we need to highlight what we mean by ethics and the key points/aspects that people need to be aware of, alongside pointers to further resources.

There are some important questions asked in the above comments but, for some of them at least, I don't know that we can yet (or maybe can ever) answer them - at least in terms of clear, concrete answers?

I think the text provided by @mhagdorn in #79 is great so maybe we can go with this as a start and then try and come up with a list of any points that we feel need to be represented in the paper but are not covered there?

**Comment by jngrad** [comment]
Suggestion from the paper meeting: briefly mention software citation.

Resources shared in the chat about RSE output assessment:
* https://www.se-rwth.de/publications/Toward-Research-Software-Engineering-Research-Preprint.pdf
   * RSE Research : conducting research on understanding and improving how software is developed for research
* https://sfdora.org/
   * The Declaration on Research Assessment (DORA) recognizes the need to improve the ways in which researchers and the outputs of scholarly research are evaluated
* https://coara.eu/
   * Coalition for Advancing Research Assessment

**Comment by mhagdorn** [comment]
My main reason for including notes on ethics is that RSEs need to be aware of the issues such as the various biases that come into play when training models or privacy implications when dealing with spatial data. RSE need to make personal value calls just like any other researcher. What others do with a particular software project is an entirely different problem (and depends on them being sensitised to these issues). I think in the context of this paper we need to state the basics and provide signposts to furhter reading.

**Comment by mhagdorn** [comment]
just came across this on Wissenschaftliche Integrität from the DFG

https://wissenschaftliche-integritaet.de/kodex/

**Comment by hvwaldow** [comment]
> just came across this on Wissenschaftliche Integrität from the DFG
> 
> https://wissenschaftliche-integritaet.de/kodex/

bisschen zu deutsch ...

**Comment by mhagdorn** [comment]
and another great paper that we should include somehow...
https://link.springer.com/article/10.1007/s11948-017-9961-8
