### ISSUE TITLE
Actually split up the paper

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#88]
We decided to split up the paper into four separate entities.
To that end, I will merge as I see fit, and reopen and assign new issues.

**Comment by CaptainSifff** [comment]
- revive funder acknowledgement thread: https://github.com/CaptainSifff/paper_teaching-learning-RSE/pull/77

**Comment by CaptainSifff** [comment]
silly me did the splitting in the main branch...

**Comment by MakisH** [comment]
The paper has already been split to four different papers, see current README: https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/9e09cfd22a53cd3fdfea5621a3230413aeba1392/README.md
