### ISSUE TITLE
intro + abstract - survey

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#92]
survey.md contains the survey on the existing resources in the RSE space. Currently it only contains a dummy abstract and lacks an introduction. So someone needs to provide one.

**Comment by jngrad** [comment]
Some work was started in PR #101.

**Comment by samumantha** [comment]
Sorry I was not able to join the last few meetings and am will not be able to join until mid September. Splitting seems like a great new way. What I did not find is what kind of style this document should be: scientific publication, blog post, ..? What is the target audience here?

**Comment by jngrad** [comment]
The new file [related-work-training.md](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/933ef486767cf573d7e473d847fa686b7b40a47c/related-work-training.md) is mostly identical to [survey.md](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/933ef486767cf573d7e473d847fa686b7b40a47c/survey.md) and partially overlaps with [competencies.md](https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/933ef486767cf573d7e473d847fa686b7b40a47c/competencies.md).

**Comment by CaptainSifff** [comment]
I feel this has been resolved.
