### ISSUE TITLE
intro + abstract - competencies

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#93]
competencies.md contains the discussion on the competencies, the specializations and probably the appendix with the examples. Also the tables. Currently it lacks a proper abstract and an introduction, although I think, a lot can be recycled from intro.md which contains the old intro.

**Comment by jpthiele** [comment]
@jcohen02 I started a new branch with an initial version for the intro. 
Feel free to discuss, change or expand

**Comment by mhagdorn** [comment]
I've got a couple of hours without reliable internet today and will have a little go at this as well

**Comment by mhagdorn** [comment]
> I've got a couple of hours without reliable internet today and will have a little go at this as well

actually I didn't have that much time and I found that @jcohen02 assigned an action to me, so nothing pending from me here.
