### ISSUE TITLE
Suresoft - continued

### ISSUE THREAD

**Issue by CaptainSifff** [CaptainSifff/paper_teaching-learning-RSE#99]
@jlinx: @braunms has contributed sth. on suresoft in https://github.com/CaptainSifff/paper_teaching-learning-RSE/pull/67
Do you want ot contribute sth. here?

**Comment by MakisH** [comment]
There was a nicely long paragraph in the Competencies paper, which was compressed into a short mention and then moved to this file for future usage: https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/6f793779f36897f0dbc35fab4843b5429b85ced3/related-work-training.md#suresoft

I understand this issue as closed.
